#!/usr/bin/env python3
r"""Small, dependency-free live dashboard for COSMOKE UDP telemetry.

Run from the project root:
    python .\Tools\cosmoke_dashboard.py
"""

from __future__ import annotations

import argparse
import csv
import queue
import socket
import threading
import time
from collections import deque
from datetime import datetime, timezone
from pathlib import Path

try:
    import tkinter as tk
    from tkinter import messagebox
except ImportError as error:  # pragma: no cover - depends on the local Python install
    raise SystemExit("tkinter가 포함된 Python이 필요합니다. 일반 Windows Python 설치본을 사용하세요.") from error

from cosmoke_udp_monitor import (
    CAPTURE_COLUMNS,
    PACKET_SIZE,
    SequenceStats,
    capture_row,
    decode_binary,
    flag_text,
)


CSV_FIELDS = (
    "sequence", "milliseconds", "flags", "adc_status",
    "i1", "v1", "i2", "v2",
    "raw_i1", "raw_v1", "raw_i2", "raw_v2",
    "dac_i1", "dac_v1", "dac_i2", "dac_v2",
    "dropped", "crc_errors", "spi_errors", "dac_errors",
)


def decode_csv(packet: bytes) -> dict:
    """Decode the default 20-field CSV datagram generated by the firmware."""
    text = packet.decode("ascii").strip()
    values = text.split(",")
    if len(values) != len(CSV_FIELDS):
        raise ValueError(f"CSV field count is {len(values)}, expected {len(CSV_FIELDS)}")
    result = {name: int(value, 0) for name, value in zip(CSV_FIELDS, values)}
    result["raw_csv"] = text
    result["format"] = "CSV"
    return result


def decode_packet(packet: bytes) -> dict:
    """Automatically decode the firmware's default CSV or optional binary packet."""
    if len(packet) == PACKET_SIZE and packet[:2] == b"\x5a\xa5":
        decoded = decode_binary(packet)
        result = {
            "sequence": decoded["sequence"],
            "milliseconds": decoded["milliseconds"],
            "flags": decoded["flags"],
            "adc_status": decoded["adc_status"],
            "i1": decoded["scaled"][0], "v1": decoded["scaled"][1],
            "i2": decoded["scaled"][2], "v2": decoded["scaled"][3],
            "raw_i1": decoded["raw"][0], "raw_v1": decoded["raw"][1],
            "raw_i2": decoded["raw"][2], "raw_v2": decoded["raw"][3],
            "dac_i1": decoded["dac"][0], "dac_v1": decoded["dac"][1],
            "dac_i2": decoded["dac"][2], "dac_v2": decoded["dac"][3],
            "raw": decoded["raw"], "scaled": decoded["scaled"], "dac": decoded["dac"],
            "dropped": decoded["dropped"], "crc_errors": decoded["crc_errors"],
            "spi_errors": None, "dac_errors": None,
            "raw_csv": "(64 B binary packet)", "format": "BINARY",
        }
        return result
    return decode_csv(packet)


class UdpReceiver(threading.Thread):
    def __init__(self, bind: str, port: int, output: queue.Queue, stop: threading.Event):
        super().__init__(daemon=True)
        self.bind, self.port, self.output, self.stop = bind, port, output, stop

    def run(self) -> None:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as receiver:
            receiver.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            receiver.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
            receiver.settimeout(0.4)
            try:
                receiver.bind((self.bind, self.port))
            except OSError as error:
                self.output.put(("error", f"UDP {self.bind}:{self.port}를 열 수 없습니다: {error}"))
                return

            self.output.put(("ready", None))
            while not self.stop.is_set():
                try:
                    packet, peer = receiver.recvfrom(2048)
                except socket.timeout:
                    continue
                except OSError as error:
                    if not self.stop.is_set():
                        self.output.put(("error", str(error)))
                    return
                try:
                    frame = decode_packet(packet)
                    frame["peer"] = peer[0]
                    frame["peer_address"] = peer
                    frame["received_at"] = datetime.now(timezone.utc)
                    self.output.put(("frame", frame))
                except (UnicodeDecodeError, ValueError, KeyError) as error:
                    self.output.put(("decode_error", str(error)))


class MetricCard(tk.Frame):
    def __init__(self, parent: tk.Misc, title: str, color: str):
        super().__init__(parent, bg="#14253a", padx=18, pady=14, highlightthickness=1,
                         highlightbackground="#2b4661")
        tk.Label(self, text=title, font=("Segoe UI", 11, "bold"), fg=color, bg="#14253a").pack(anchor="w")
        self.value = tk.StringVar(value="—")
        self.sub = tk.StringVar(value="waiting")
        tk.Label(self, textvariable=self.value, font=("Segoe UI", 26, "bold"), fg="#f5f9ff", bg="#14253a").pack(anchor="w", pady=(7, 0))
        tk.Label(self, textvariable=self.sub, font=("Segoe UI", 9), fg="#9eb6cd", bg="#14253a").pack(anchor="w")

    def set(self, value: int, unit: str) -> None:
        scaled = value / 1000.0
        self.value.set(f"{scaled:.3f} {unit}")
        self.sub.set(f"{value:+d} {unit.lower().replace('a', 'mA').replace('v', 'mV')}")


class Sparkline(tk.Canvas):
    def __init__(self, parent: tk.Misc, title: str, unit: str, color: str, min_span: int = 100):
        super().__init__(parent, height=145, bg="#14253a", highlightthickness=1,
                         highlightbackground="#2b4661")
        self.title, self.unit, self.color, self.min_span, self.values = title, unit, color, min_span, ()
        self.bind("<Configure>", lambda _event: self.draw())

    def set_values(self, values) -> None:
        self.values = tuple(values)
        self.draw()

    def draw(self) -> None:
        self.delete("all")
        width, height = max(self.winfo_width(), 20), max(self.winfo_height(), 40)
        self.create_text(12, 12, text=f"{self.title} ({self.unit})", anchor="w", fill="#d7e7f7", font=("Segoe UI", 10, "bold"))
        if len(self.values) < 2:
            self.create_text(width / 2, height / 2, text="data waiting", fill="#6f8ba6", font=("Segoe UI", 10))
            return
        low, high = min(self.values), max(self.values)
        span = high - low
        if span < self.min_span:
            mid = (high + low) / 2.0
            half = self.min_span / 2.0
            low_f = mid - half
            high_f = mid + half
        else:
            low_f = float(low)
            high_f = float(high)

        pad_x, top, bottom = 12, 31, 20
        span_y = height - top - bottom
        span_val = high_f - low_f
        if span_val <= 0:
            span_val = 1.0
        points = []
        for index, value in enumerate(self.values):
            x = pad_x + index * (width - 2 * pad_x) / (len(self.values) - 1)
            y = top + (high_f - value) * span_y / span_val
            points.extend((x, y))
        self.create_line(*points, fill=self.color, width=2)
        self.create_text(width - 10, 12, text=f"{self.values[-1]:+d} {self.unit}", anchor="e", fill="#9eb6cd", font=("Segoe UI", 9))
        self.create_text(width - 10, height - 9, text=f"range {int(round(low_f)):+d}…{int(round(high_f)):+d} {self.unit}", anchor="e", fill="#6f8ba6", font=("Segoe UI", 8))


class Dashboard:
    def __init__(self, bind: str, port: int):
        self.root = tk.Tk()
        self.root.title("COSMOKE LAN Dashboard")
        self.root.geometry("1120x750")
        self.root.minsize(900, 620)
        self.root.configure(bg="#0b1726")
        self.queue: queue.Queue = queue.Queue()
        self.stop = threading.Event()
        self.receiver = UdpReceiver(bind, port, self.queue, self.stop)
        self.last_frame_time = None
        self.packet_count = 0
        self.histories = {name: deque(maxlen=120) for name in ("i1", "v1", "i2", "v2")}
        self.capture_file = None
        self.capture_writer = None
        self.capture_path: Path | None = None
        self.capture_stats = SequenceStats()

        self.connection = tk.StringVar(value=f"LISTENING  {bind}:{port}")
        self.connection_detail = tk.StringVar(value="UDP packet waiting…")
        self.flags = tk.StringVar(value="—")
        self.adc = tk.StringVar(value="ADC status: —")
        self.counters = tk.StringVar(value="Dropped: —   CRC: —   SPI: —   DAC: —")
        self.latest = tk.StringVar(value="Latest datagram: waiting")
        self.capture_status = tk.StringVar(value="CSV 저장: 대기")

        self._build()
        self.start_capture()
        self.receiver.start()
        self.root.after(30, self.poll)
        self.root.after(250, self.update_age)
        self.root.protocol("WM_DELETE_WINDOW", self.close)

    def _build(self) -> None:
        header = tk.Frame(self.root, bg="#0f7c86", padx=22, pady=15)
        header.pack(fill="x")
        tk.Label(header, text="COSMOKE  |  LAN LIVE DASHBOARD", font=("Segoe UI", 18, "bold"),
                 fg="white", bg="#0f7c86").pack(anchor="w")
        tk.Label(header, textvariable=self.connection, font=("Segoe UI", 10, "bold"), fg="#d7fbff", bg="#0f7c86").pack(anchor="w", pady=(3, 0))

        body = tk.Frame(self.root, bg="#0b1726", padx=18, pady=16)
        body.pack(fill="both", expand=True)
        body.grid_columnconfigure((0, 1, 2, 3), weight=1, uniform="metric")

        self.cards = [
            MetricCard(body, "CH1 CURRENT", "#49dcb1"), MetricCard(body, "CH1 VOLTAGE", "#78b8ff"),
            MetricCard(body, "CH2 CURRENT", "#f6bd60"), MetricCard(body, "CH2 VOLTAGE", "#ef8cb5"),
        ]
        for index, card in enumerate(self.cards):
            card.grid(row=0, column=index, sticky="nsew", padx=5, pady=(0, 12))

        status = tk.Frame(body, bg="#14253a", padx=16, pady=12, highlightthickness=1, highlightbackground="#2b4661")
        status.grid(row=1, column=0, columnspan=4, sticky="ew", padx=5, pady=(0, 12))
        status.grid_columnconfigure(1, weight=1)
        tk.Label(status, text="STATUS", font=("Segoe UI", 10, "bold"), fg="#8fe6d0", bg="#14253a").grid(row=0, column=0, sticky="w")
        tk.Label(status, textvariable=self.flags, font=("Segoe UI", 11, "bold"), fg="#f5f9ff", bg="#14253a").grid(row=0, column=1, sticky="w", padx=14)
        tk.Label(status, textvariable=self.adc, font=("Consolas", 10), fg="#b8cae0", bg="#14253a").grid(row=0, column=2, sticky="e")
        tk.Label(status, textvariable=self.connection_detail, font=("Segoe UI", 10), fg="#b8cae0", bg="#14253a").grid(row=1, column=0, columnspan=3, sticky="w", pady=(8, 0))
        tk.Label(status, textvariable=self.counters, font=("Consolas", 10), fg="#b8cae0", bg="#14253a").grid(row=2, column=0, columnspan=3, sticky="w", pady=(5, 0))

        charts = tk.Frame(body, bg="#0b1726")
        charts.grid(row=2, column=0, columnspan=4, sticky="nsew")
        charts.grid_columnconfigure((0, 1), weight=1, uniform="chart")
        self.charts = [
            Sparkline(charts, "CH1 current history", "mA", "#49dcb1", min_span=100),
            Sparkline(charts, "CH1 voltage history", "mV", "#78b8ff", min_span=1000),
            Sparkline(charts, "CH2 current history", "mA", "#f6bd60", min_span=100),
            Sparkline(charts, "CH2 voltage history", "mV", "#ef8cb5", min_span=1000),
        ]
        for index, chart in enumerate(self.charts):
            chart.grid(row=index // 2, column=index % 2, sticky="nsew", padx=5, pady=5)

        footer = tk.Frame(body, bg="#0b1726")
        footer.grid(row=3, column=0, columnspan=4, sticky="ew", padx=5, pady=(12, 0))
        footer.grid_columnconfigure(0, weight=1)
        tk.Label(footer, textvariable=self.latest, justify="left", anchor="w", wraplength=870,
                 font=("Consolas", 9), fg="#9eb6cd", bg="#0b1726").grid(row=0, column=0, sticky="ew")
        tk.Button(footer, text="Clear trend", command=self.clear_trend, bg="#254761", fg="white",
                  activebackground="#326783", activeforeground="white", relief="flat", padx=12, pady=6).grid(row=0, column=1, padx=(12, 0))
        tk.Label(footer, textvariable=self.capture_status, justify="left", anchor="w",
                 font=("Segoe UI", 9, "bold"), fg="#8fe6d0", bg="#0b1726").grid(row=1, column=0, sticky="ew", pady=(10, 0))
        self.start_capture_button = tk.Button(
            footer, text="새 CSV 저장", command=self.start_capture, bg="#0f7c86", fg="white",
            activebackground="#1496a1", activeforeground="white", relief="flat", padx=12, pady=6,
        )
        self.start_capture_button.grid(row=1, column=1, padx=(12, 0), pady=(8, 0), sticky="e")
        self.stop_capture_button = tk.Button(
            footer, text="저장 종료", command=self.stop_capture, bg="#7f1d1d", fg="white",
            activebackground="#b91c1c", activeforeground="white", relief="flat", padx=12, pady=6,
            state="disabled",
        )
        self.stop_capture_button.grid(row=1, column=2, padx=(8, 0), pady=(8, 0), sticky="e")

    def poll(self) -> None:
        newest = None
        while True:
            try:
                kind, payload = self.queue.get_nowait()
            except queue.Empty:
                break
            if kind == "frame":
                self.record_capture(payload)
                newest = payload
            elif kind == "error":
                self.connection.set("UDP ERROR")
                self.connection_detail.set(payload)
            elif kind == "decode_error":
                self.connection_detail.set(f"Ignored non-COSMOKE datagram: {payload}")
        if newest:
            self.show_frame(newest)
        self.root.after(30, self.poll)

    def start_capture(self) -> None:
        if self.capture_file is not None:
            return
        logs_dir = Path.cwd() / "logs"
        logs_dir.mkdir(parents=True, exist_ok=True)
        file_name = datetime.now().strftime("cosmoke_capture_%Y%m%d_%H%M%S_%f.csv")
        self.capture_path = logs_dir / file_name
        self.capture_file = self.capture_path.open("w", newline="", encoding="utf-8")
        self.capture_writer = csv.DictWriter(self.capture_file, fieldnames=CAPTURE_COLUMNS)
        self.capture_writer.writeheader()
        self.capture_file.flush()
        self.capture_stats = SequenceStats()
        self.capture_status.set(f"CSV 저장 중: {self.capture_path.name}  ·  0 frames")
        self.start_capture_button.configure(state="disabled")
        self.stop_capture_button.configure(state="normal")

    def record_capture(self, frame: dict) -> None:
        if self.capture_writer is None or self.capture_file is None:
            return
        row = capture_row(
            frame,
            frame["peer_address"],
            frame["format"].lower(),
            frame["received_at"],
        )
        self.capture_writer.writerow(row)
        self.capture_file.flush()
        self.capture_stats.add(row["sequence"], row["device_ms"])
        self.capture_status.set(
            f"CSV 저장 중: {self.capture_path.name}  ·  {self.capture_stats.frames:,} frames"
        )

    def stop_capture(self, show_notice: bool = True) -> None:
        if self.capture_file is None:
            return
        self.capture_file.close()
        summary = (
            f"{self.capture_path.name} 저장 완료 · {self.capture_stats.frames:,} frames · "
            f"추정 UDP 유실 {self.capture_stats.lost:,} · "
            f"재부팅/역순 {self.capture_stats.resets_or_reorders:,}"
        )
        self.capture_file = None
        self.capture_writer = None
        self.capture_status.set(summary)
        self.start_capture_button.configure(state="normal")
        self.stop_capture_button.configure(state="disabled")
        if show_notice:
            messagebox.showinfo("CSV 저장 완료", f"{summary}\n\n저장 위치:\n{self.capture_path}")

    def show_frame(self, frame: dict) -> None:
        self.last_frame_time = time.monotonic()
        self.packet_count += 1
        for history, name in zip(self.histories.values(), ("i1", "v1", "i2", "v2")):
            history.append(frame[name])
        self.cards[0].set(frame["i1"], "A")
        self.cards[1].set(frame["v1"], "V")
        self.cards[2].set(frame["i2"], "A")
        self.cards[3].set(frame["v2"], "V")
        for chart, history in zip(self.charts, self.histories.values()):
            chart.set_values(history)
        flags = frame["flags"]
        flag_description = flag_text(flags)
        if flags & (1 << 12):
            state_label = "[MUTED]"
        elif flags & (1 << 13):
            state_label = "[WARMUP]"
        elif flags == 0x0001:
            state_label = "[ACTIVE/OK]"
        else:
            state_label = "[CHECK]"
        self.flags.set(f"{state_label}  {flags:#06x}  {flag_description}")
        self.adc.set(f"ADC status: {frame['adc_status']:#06x}  ·  {frame['format']}")
        spi = "—" if frame["spi_errors"] is None else str(frame["spi_errors"])
        dac = "—" if frame["dac_errors"] is None else str(frame["dac_errors"])
        self.counters.set(f"Dropped: {frame['dropped']}   CRC: {frame['crc_errors']}   SPI: {spi}   DAC Failed Cycles: {dac}")
        self.connection.set(f"LIVE  ·  {frame['peer']} → UDP 5000  ·  {self.packet_count} packets")
        self.connection_detail.set(f"Sequence {frame['sequence']:,}  ·  board time {frame['milliseconds']:,} ms  ·  last packet now")
        self.latest.set(f"Latest datagram: {frame['raw_csv']}")

    def update_age(self) -> None:
        if self.last_frame_time is None:
            self.connection_detail.set("UDP packet waiting…  Check RJ45 link, PC address, then firmware.")
        else:
            age = time.monotonic() - self.last_frame_time
            if age > 1.5:
                self.connection.set("STALE  ·  last packet timed out")
                self.connection_detail.set(f"Last packet {age:.1f} seconds ago. Check Ethernet connection.")
        self.root.after(250, self.update_age)

    def clear_trend(self) -> None:
        for history in self.histories.values():
            history.clear()
        for chart in self.charts:
            chart.set_values(())

    def close(self) -> None:
        self.stop_capture(show_notice=False)
        self.stop.set()
        self.root.destroy()

    def run(self) -> None:
        self.root.mainloop()


def main() -> int:
    parser = argparse.ArgumentParser(description="COSMOKE UDP live dashboard")
    parser.add_argument("--bind", default="0.0.0.0", help="PC listen address (default: 0.0.0.0)")
    parser.add_argument("--port", type=int, default=5000, help="UDP port (default: 5000)")
    args = parser.parse_args()
    Dashboard(args.bind, args.port).run()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
